version: '3'
services:
  indexmap:
    build: ./FAISS
    ports:
      - "5001:5001"
    volumes:
      - ./FAISS:/media/code
      - /media/axhue/WD/Data/Coronawhy/:/media/data #change this to data directory
    environment:
      FLASK_ENV: development
      FLASK_APP: /media/code/app.py
      FLASK_RUN_PORT: 5001
  langmodel:
    build: ./Language_model
    volumes:
      - ./Language_model:/media/code
      - /media/axhue/WD/Data/Coronawhy/:/media/data #change this to data directory
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: /media/code/app.py
      FLASK_RUN_PORT: 5000