version: '3'
services:
  indexmap:
    build: ./faiss
    ports:
      - "5001:5001"
    volumes:
      - ./faiss:/media/code
      - /data:/media/data #change this to data directory
    environment:
      FLASK_ENV: development
      FLASK_APP: /media/code/app.py
      FLASK_RUN_PORT: 5001
  langmodel:
    build: ./language_model
    volumes:
      - ./language_model:/media/code
      - /data:/media/data #change this to data directory
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_APP: /media/code/app.py
      FLASK_RUN_PORT: 5000
